# Generated by Django 2.2.6 on 2019-10-30 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_movie_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='email',
            field=models.EmailField(max_length=100),
        ),
    ]
